<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/protos/v1/hallo.proto

namespace Protobuf\Hallo\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>hallo.v1.ReqHallo</code>
 */
class ReqHallo extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protobuf\Protos\V1\Hallo::initOnce();
        parent::__construct($data);
    }

}

