<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hallo.proto

namespace grpc\GPBMetadata;

class Hallo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0Az\x0A\x0Bhallo.proto\x12\x05hallo\"\x0A\x0A\x08ReqHallo\"/\x0A\x08ResHallo\x12\x12\x0A\x0Ais_success\x18\x01 \x01(\x08\x12\x0F\x0A\x07message\x18\x02 \x01(\x09B\x1FZ\x0Fgen/proto;proto\xCA\x02\x0BProto\\Hallob\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

