<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/health.proto

namespace GPBMetadata\V1;

class Health
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
�
v1/health.proto	health.v1"D
	ReqHealth
message (	
in_progress (
	timestamp ("0
	ResHealth

is_success (
message (	B:Z8github.com/bit-craft-io/sandbox/gs/gen/healthpb;healthpbbproto3'
        , true);

        static::$is_initialized = true;
    }
}

