<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/protos/v1/hallo.proto

namespace GPBMetadata\Protobuf\Protos\V1;

class Hallo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¡
protobuf/protos/v1/hallo.protohallo.v1"

ReqHallo"/
ResHallo

is_success (
message (	BPZ:internal.local/bit-craft-io/sandbox/gs/gen/hallopb;hallopb Protobuf\\Hallo\\V1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

