<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/protos/v1/health.proto

namespace GPBMetadata\Protobuf\Protos\V1;

class Health
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Å
protobuf/protos/v1/health.proto	health.v1"D
	ReqHealth
message (	
in_progress (
	timestamp ("0
	ResHealth

is_success (
message (	BSZ<internal.local/bit-craft-io/sandbox/gs/gen/healthpb;healthpb Protobuf\\Health\\V1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

