<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hallo.proto

namespace Proto\Hallo;

/**
 * Generated from protobuf message <code>hallo.ReqHallo</code>
 */
class ReqHallo extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \grpc\GPBMetadata\Hallo::initOnce();
        parent::__construct($data);
    }

}

